services:
  backend:
    image: ghcr.io/oxiareliion/web-tasarim-proje-frontend-backend:latest
    container_name: app-backend
    ports:
      - "8000:8000"
    env_file:
      - ./BACKEND/.env
    restart: unless-stopped

  frontend:
    image: ghcr.io/oxiareliion/web-tasarim-proje-frontend-frontend:latest
    container_name: app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
